# -*- coding: utf-8 -*-
"""Load InfoWorks simulation output and associated information and prepare them for calibration and evaluation.

Created on Tue Feb 24 13:07:46 2026
@author: Way
"""

import os
import pandas as pd

# Keys for InfoWorks ICM-generated column header for each output variable.
ETa_key = "pdm_evaporation"
smd_key = "pdm_smd"
quickflow_key = "pdm_surfaceflow"
baseflow_key = "pdm_baseflow"

class Simulation:
    """Container for a simulation's identifier, its associated parameters, the InfoWorks output time-series, and plotting parameters
    
    Parameters
    ----------
    excel_row : pandas.Series
        One row from the simulation configuration excel containing simulation metadata, parameter values, and other related variables.
    sim_path : str
        Path to folder containing the InfoWorks simulation output files.
    
    Attributes
    ----------
    name : str
        Unique identifier for a simulation (simulation_id), used to label this simulation in plots and evaluation output.
    calibration_target : str
        The submodel this simulation is to be calibrated
        ("ETa", "soil", "runoff", or "recession").
    ETa_mmday, smd : pandas.Series
        Actual evapotranspiration and soil moisture deficit time-series (only when calibration_target is "ETa" or "soil").
    BF_m3s, QF_m3s : pandas.Series
        Loaded baseflow and quickflow time-series (only when calibration_target is not "ETa" or "soil").
    λ_SWd, λ_QF, λ_BF : float
        Box-Cox transformation lambda parameters for soil water depth, quickflow, and baseflow, used in Box-Cox plotting.
    parameters : dict
        The simulation parameter set from the configuration Excel.
    
    """
    def __init__(self, excel_row, sim_path):
        row_dict = excel_row.to_dict()                                                 # Numbers: order of column in simulation configuration excel
        
        # Fields below are not stored as variable here, they only to filter rows in calibration.py
        row_dict.pop('catchment')                                                      # 2
        row_dict.pop('period_id')                                                      # 3
        row_dict.pop('stage')                                                          # 4
        row_dict.pop('evaluation_method')                                              # 6
        row_dict.pop('flowtype')                                                       # 7
        
        # Field below are stored as variables, used here and in calibration.py
        self.name = row_dict.pop('simulation_id')                                      # 1
        self.calibration_target = row_dict.pop('calibration_target')                   # 5
        
        # Load filename to be joined as path
        ETa_soilmoisture_filename = row_dict.pop('ETa_soilmoisture_filename')          # 8
        baseflow_quickflow_filename = row_dict.pop('baseflow_quickflow_filename')      # 9
        
        if self.calibration_target in ["ETa", "soil"]:
            self.ETa_mmday = self.load_timeseries(sim_path, ETa_soilmoisture_filename, ETa_key)
            self.smd = self.load_timeseries(sim_path, ETa_soilmoisture_filename, smd_key)
        
        else:
            self.BF_m3s = self.load_timeseries(sim_path, baseflow_quickflow_filename, baseflow_key)
            self.QF_m3s = self.load_timeseries(sim_path, baseflow_quickflow_filename, quickflow_key)
        
        self.λSWd = row_dict.pop("λSWd")                                               # 10
        self.λQF = row_dict.pop("λQF")                                                 # 11
        self.λBF = row_dict.pop("λBF")                                                 # 12
        
        self.parameters = row_dict                                                     # "parameters" Sheet
        
    def load_timeseries(self, folder, filename, columnkey):
        """Extract the time-series from InfoWorks output files and prepare them for use in calibration.
        
        Parameters
        ----------
        folder : str
            Path of the folder that stores the InfoWorks output files.
        filename : str
            The filename of the InfoWorks output file.
        columnkey : str
            The column header of the time-series.

        Raises
        ------
        ValueError
            When the column header generated by InfoWorks does not match the provided key above.

        Returns
        -------
        pandas.Series
            Time-series of output variables (ET, soil moisture, subflows).
        """

        file = os.path.join(folder, filename)
        df = pd.read_csv(file, skiprows = 1) # column header in the output excel generated from InfoWorks is the second row
        
        df["Timestamp"] = pd.to_datetime(                          
            df["Date"].astype(str) + " " + df["Time"].astype(str), 
            dayfirst = True                                        
        )
        
        df = df.set_index("Timestamp")                             
        
        # Find the InfoWorks output column containing the specified key.
        column_name = [column                   
                       for column in df.columns 
                       if columnkey in column]  
        
        # Raise an error if the expected output column is not found.
        if not column_name:
            raise ValueError("no column header found")
        
        column = column_name[0]
        return df[column] 